# Generated by Django 2.2.5 on 2019-09-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF no formato 999.999.999-99', max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
