# Generated by Django 2.2.5 on 2019-12-12 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, max_length=128, null=True, verbose_name='Nome')),
                ('sigla', models.TextField(blank=True, max_length=10, null=True, verbose_name='Sigla')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('descricao', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Descricao do evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descricao do ingresso')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor do ingresso')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.Evento')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, max_length=128, null=True, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('cpf', models.TextField(blank=True, help_text='No formato 999.999.999-99', max_length=14, null=True, verbose_name='CPF')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.Evento')),
                ('ingresso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.Ingresso')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.Pessoa')),
            ],
            options={
                'verbose_name': 'Inscricao',
                'verbose_name_plural': 'Inscricoes',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.Pessoa'),
        ),
    ]
