# Generated by Django 2.2.4 on 2019-10-04 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=124, null=True, verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroProtocolo', models.CharField(blank=True, max_length=24, null=True, verbose_name='Numero de protocolo do Documento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do documento')),
                ('nome', models.CharField(blank=True, max_length=246, null=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=124, null=True, verbose_name='Nome')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('telefone_celular', models.CharField(blank=True, help_text='Numero de telefone celular no formato (99) 99999-9999', max_length=15, null=True, verbose_name='Telefone celular')),
                ('telefone_fixo', models.CharField(blank=True, help_text='Numero de telefone fixo no formato (99) 9999-9999', max_length=15, null=True, verbose_name='Telefone celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, help_text='CPF no formato 999.999.999-99', max_length=14, null=True, verbose_name='CPF')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Numero no modelo 9999999.99.9999.9.99.9999', max_length=25, null=True, verbose_name='Numero do processo')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data criacao')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Departamento')),
                ('interessados', models.ManyToManyField(related_name='Interessados', to='app_processo.Pessoa')),
                ('investigados', models.ManyToManyField(related_name='Investigados', to='app_processo.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Pessoa')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matricula')),
                ('funcao', models.CharField(blank=True, max_length=124, null=True, verbose_name='Funcao')),
            ],
            bases=('app_processo.pessoa',),
        ),
        migrations.CreateModel(
            name='Instauracao',
            fields=[
                ('documentos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documentos')),
                ('dataInstauracao', models.DateField(blank=True, null=True, verbose_name='Data de instauracao')),
            ],
            bases=('app_processo.documentos',),
        ),
        migrations.CreateModel(
            name='PedidoPrazo',
            fields=[
                ('documentos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documentos')),
                ('prazoAnt', models.DateField(blank=True, null=True, verbose_name='Data de prazo anterior')),
                ('prazoAtual', models.DateField(blank=True, null=True, verbose_name='Date de prazo novo')),
                ('justificativa', models.TextField(max_length=1024, verbose_name='Justificativa de Pedido')),
            ],
            bases=('app_processo.documentos',),
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataMov', models.DateField(blank=True, null=True, verbose_name='Data de movimentacao')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Destino', to='app_processo.Departamento')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Origem', to='app_processo.Departamento')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='documentos',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Funcionario'),
        ),
        migrations.CreateModel(
            name='EnvioProcesso',
            fields=[
                ('documentos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documentos')),
                ('dataEnvio', models.DateField(blank=True, null=True, verbose_name='Data de Envio')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Departamento')),
            ],
            bases=('app_processo.documentos',),
        ),
        migrations.AddField(
            model_name='documentos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Funcionario'),
        ),
    ]
