# Generated by Django 2.2.5 on 2019-12-10 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0005_auto_20191210_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='pessoa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_noticias.Pessoa'),
        ),
    ]
